server:
  servlet:
    context-path: /example

telegram:
  botName: "EasyTickets"
  token: ${TELEGRAM_TOKEN}


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./build/db
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update