server:
  servlet:
    context-path: /example

telegram:
  botName: "EasyTickets"
  token: ${TELEGRAM_TOKEN}


spring:
  datasource:
    #driver-class-name: tech.ydb.jdbc.YdbDriver
    driver-class-name: org.h2.Driver
    #url: jdbc:ydb:grpcs://ydb.serverless.yandexcloud.net:2135/?database=/ru-central1/b1giu1cmr19b28ml1f58/etnt5gaeuubi9uf5qifb?saFile=file:~/sa_key.json
    url: jdbc:h2:file:./build/db
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: tech.ydb.hibernate.dialect.YdbDialect