server:
  servlet:
    context-path: /example
  port: 8083

telegram:
  botName: "EasyTickets"
  token: ${TELEGRAM_TOKEN}


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1b-2chvmuve31k65h4j.mdb.yandexcloud.net:6432/easy-tickets-main?targetServerType=master
    username: dksu
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        dialect: tech.ydb.hibernate.dialect.YdbDialect